# Generated by Django 4.2.1 on 2023-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdukItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=255)),
                ('harga', models.FloatField()),
                ('harga_diskon', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='product_picts')),
                ('label', models.CharField(choices=[('BS', 'best seller'), ('BQ', 'best quality')], max_length=4)),
                ('kategori', models.CharField(choices=[('1', 'Computer'), ('2', 'Accesories')], max_length=2)),
            ],
        ),
    ]
