# Generated by Django 4.2.1 on 2023-05-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pengguna", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pembeli",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("alamat", models.TextField()),
                ("no_hp", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="produkitem",
            name="gambar",
            field=models.ImageField(null=True, upload_to="product_picts"),
        ),
    ]
